site_name: Michael Scarborough Technical Writing Portfolio
site_url: https://MackMike.github.io/technical-writing-portfolio-site/
theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Resume: resume.md
  - Projects:
      - Atari Computer User Guide: projects/atari-user-guide.md
      - Migrate User Administrative Tool Documentation: projects/migrate-user.md
      - Apache OpenOffice Technical Editing: projects/openoffice-technical-editing.md
      - Managed macOS Onboarding Guide: projects/managed-mac-onboarding.md
      - Troubleshooting Compliance Failures on Jamf-Managed Macs: projects/jamf-managed-mac-compliance-troubleshooting.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details